Representing new file layout in segment table
LOAD segments match the offsets of their corresponding section.
Exception: The PHDR table.  The PHDR table residents at the moment at
the end of the file and is loaded to its old place in address space (and
messes probably with the following sections due to its new size).